Add Cloud Build configurations for non Linux users
GoogleCloudPlatform/opentelemetry-cloud-run pull request #4
Opened 2023-06-06 06:44 UTC by ymotongpoo

Fixes #3 

* Add Cloud Build configuration
* Add policy.yaml to update the service to allow unauthenticated access
* Add init.sh and cleanup.sh to automate prerequisites set up and clean up
* Update README to explain the Cloud Build support

2023-06-09 11:46 UTC, damemi requested changes
thanks @ymotongpoo, just one typo then lgtm

2023-06-09 11:46 UTC, damemi commented on README.md
> +##### Buildthe sample app
```suggestion
##### Build the sample app
```

2023-06-12 12:30 UTC, ymotongpoo commented
@damemi Thank you, Mike for reviewing this PR! I forgot the comment after updating, so I'm surprised to hear back from you in such a short round trip!

2023-06-12 14:22 UTC, damemi approved these changes

2023-06-12 14:22 UTC, merged